config/routes.rb
Rails.application.routes.draw do
  resources :beers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

    def index
        @beers = Beer.all
    end

    def show
        @beer = Beer.find(params[:id])
    end

    def new
        @beer = Beer.new
    end

    def create
        ibu = beer_params(:ibu)[:ibu] + " IBU"
        alcohol = beer_params(:alcohol)[:alcohol] + "%"
        @beer = Beer.create(beer_params(:name, :style))
        @beer.update(ibu: ibu, alcohol: alcohol)
        redirect_to beer_path(@beer)
    end

    def edit
        @beer = Beer.find(params[:id])
    end

    def update
        @beer = Beer.find(params[:id])
        @beer.update(beer_params(:name))
        redirect_to beer_path(@beer)
    end

    def destroy
        Beer.destroy(params[:id])
        redirect_to beers_path
    end


    private

    def beer_params(*args)
        params.require(:beer).permit(*args)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/edit.html.erb
<%= form_for @beer do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %><br>
  
  
    <%= f.submit %>
  <% end %>

app/views/beers/index.html.erb
<h1>Beer List </h1>

<ul>
    <% @beers.each do |beer| %>
     <li> <%= link_to beer.name, beer_path(beer) %> </li>
    <% end %>
</ul>

app/views/beers/new.html.erb
<%= form_for @beer do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %><br />
  
    <%= f.label "Style" %>:
    <%= f.text_field :style %> <br />

    <%= f.label "IBU" %>:
    <%= f.text_field :ibu + " IBU" %> <br />

    <%= f.label :alcohol %>:
    <%= f.text_field :alcohol + "%" %> <br />
  
    <%= f.submit %>
  <% end %>

app/views/beers/show.html.erb
<h1> <%= @beer.name %> </h1>
<h3> Style: <%= @beer.style %> </h3>
<h3> IBU: <%= @beer.ibu %> </h3>
<h3> Alcohol: <%= @beer.alcohol %> </h3>
<br>
<%= button_to "Edit Beer", edit_beer_path(@beer), method: "get" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>